locales:
  pur:
    name: Purubora Keyboards
    description: >-
      Mobile OS keyboards for the Purubora language from the Divvun group
      at UiT.
  en:
    name: Purubora Keyboards
    description: >-
      Mobile OS keyboards for the Purubora language from the Divvun group
      at UiT.
  nb:
    name: Purubora tastatur
    description: Mobiltastatur for Purubora fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
